title: João Macedo's Personal Blog
description: > # this means to ignore newlines until "baseurl:"
  My blog, where I share interesting personal projects I've worked on.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: João Macedo # add your name
author-img: joao-macedo.jpg # add your photo
about-author: I'm a software engineer currently working @ di2win in research and development. I'm also currently studying in UPE. 
social-twitter: joaossmacedo # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: joaossmacedo # add your Github handle
social-linkedin: joaossmacedo # add your Linkedin handle
social-email: jssm@ecomp.poli.br # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
